# Generated by Django 4.0.4 on 2022-05-31 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parametros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veh_inicio', models.IntegerField(default=0, verbose_name='VEH inicio')),
                ('veh_fin', models.IntegerField(default=0, verbose_name='VEH fin')),
                ('veh_prefijo', models.CharField(default='', max_length=5, verbose_name='VEH prefijo')),
                ('veh_actual', models.IntegerField(default=0, verbose_name='VEH actual')),
                ('dom_inicio', models.IntegerField(default=0, verbose_name='DOM inicio')),
                ('dom_fin', models.IntegerField(default=0, verbose_name='DOM fin')),
                ('dom_prefijo', models.CharField(default='', max_length=5, verbose_name='DOM prefijo')),
                ('dom_actual', models.IntegerField(default=0, verbose_name='DOM actual')),
                ('email', models.EmailField(blank=True, max_length=264, null=True, verbose_name='Email')),
                ('password', models.CharField(blank=True, max_length=20, null=True, verbose_name='Contraseña')),
            ],
            options={
                'verbose_name_plural': 'Parametros',
            },
        ),
    ]
