# Generated by Django 4.0.4 on 2022-05-31 13:44

from django.db import migrations


def crear_registro_inicial(apps, schema_editor):
    Parametro = apps.get_model("parametros", "Parametros")
    parametro = Parametro.objects.create()

class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(crear_registro_inicial)
    ]
