# Generated by Django 4.0.4 on 2022-05-31 13:57

from django.db import migrations
from django.core.management import call_command

fixture = 'export_interface'

def crear_registros_interface(apps, schema_editor):
    call_command('loaddata', fixture, app_label='parametros')

class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0002_auto_20220531_1344'),
        # Dependencia explícita: este fixture carga un admin_interface.Theme,
        # así que esa tabla debe existir antes de intentar el loaddata. Antes
        # funcionaba "por casualidad" según el orden en que Django resolvía
        # el grafo de migraciones; quedó expuesto al agregar más apps/edges.
        ('admin_interface', '0030_theme_collapsible_stacked_inlines_and_more'),
    ]

    operations = [
        migrations.RunPython(crear_registros_interface)
    ]
