# Generated by Django 4.0.4 on 2022-06-02 12:13
from django.db import migrations

def generate_superuser(apps, schema_editor):
    """Create a new superuser """
    from django.contrib.auth import get_user_model
    from django.conf import settings

    superuser = get_user_model().objects.create_superuser(
        username=settings.DJANGO_SUPERUSER_USERNAME,
        email=settings.DJANGO_SUPERUSER_EMAIL,
        password=settings.DJANGO_SUPERUSER_PASSWORD,
    )
    superuser.save()


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0003_auto_20220531_1357'),
        # Dependencia explícita: usa get_user_model() (el modelo custom
        # completo, con todos sus campos), así que la tabla de usuarios debe
        # tener ya todas sus columnas antes del INSERT. Antes funcionaba "por
        # casualidad" porque auth_user ya existía vía las migraciones de
        # django.contrib.auth; quedó expuesto al introducir accounts.User.
        ('accounts', '0007_alter_user_cliente_final'),
    ]

    operations = [
        migrations.RunPython(generate_superuser),
    ]
