# Generated by Django 4.0.4 on 2022-05-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(verbose_name='Codigo')),
                ('cuit_cuil', models.CharField(max_length=11, verbose_name='CUIT/CUIL')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre/ Razón Social')),
                ('direccion', models.CharField(max_length=80, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=14, verbose_name='Telefono')),
                ('email', models.EmailField(blank=True, max_length=264, verbose_name='Email')),
                ('web', models.CharField(blank=True, max_length=200, verbose_name='Web')),
                ('tipo', models.CharField(choices=[('p', 'Persona'), ('e', 'Empresa')], default='p', max_length=80, verbose_name='Tipo')),
                ('estado', models.CharField(choices=[('a', 'Activo'), ('i', 'Inactivo')], default='a', max_length=80, verbose_name='Estado')),
            ],
        ),
    ]
