# Generated by Django 4.0.4 on 2022-06-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='contacto',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Nombre contacto'),
        ),
    ]
