# Generated by Django 4.0.4 on 2022-06-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_cliente_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='codigo',
            field=models.CharField(max_length=15, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cuit_cuil',
            field=models.CharField(max_length=11, null=True, verbose_name='CUIT/CUIL'),
        ),
    ]
