# Generated by Django 4.0.4 on 2022-06-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_alter_cliente_codigo_alter_cliente_cuit_cuil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=264, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='web',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Web'),
        ),
    ]
