# Generated by Django 4.0.4 on 2022-06-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_remove_cliente_id_alter_cliente_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='codigo',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Codigo'),
        ),
    ]
