# Generated by Django 4.0.4 on 2022-06-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_alter_cliente_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=80, verbose_name='Telefono'),
        ),
    ]
