# Generated by Django 4.0.4 on 2022-07-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0009_alter_cliente_direccion_alter_cliente_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='codigo',
            field=models.IntegerField(default=-1, primary_key=True, serialize=False, verbose_name='Codigo'),

        ),
    ]
