# Generated by Django 4.0.4 on 2022-09-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0011_alter_cliente_web'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cuit_cuil',
            field=models.CharField(help_text='Solo se deben ingresar numeros', max_length=11, null=True, verbose_name='CUIT/CUIL'),
        ),
    ]
