# Generated by Django 4.0.4 on 2022-10-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0012_alter_cliente_cuit_cuil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='codigo',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cuit_cuil',
            field=models.CharField(blank=True, help_text='Solo se deben ingresar numeros', max_length=11, null=True, verbose_name='CUIT/CUIL'),
        ),
    ]
