# Generated by Django 4.2.5 on 2023-09-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0013_alter_cliente_codigo_alter_cliente_cuit_cuil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='codigo',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Codigo'),
        ),
    ]
