# Generated by Django 4.2.5 on 2026-08-31 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('cliente', '0014_alter_cliente_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='empresas.company', verbose_name='Compañía'),
        ),
    ]
