# Generated by Django 5.2.17 on 2026-09-02 19:15

import datetime
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0024_alter_cliente_id'),
        ('empresas', '0003_remove_company_fecha_creacion_company_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 9, 2, 19, 15, 19, 22686, tzinfo=datetime.timezone.utc), verbose_name='Creado el'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado el'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.CreateModel(
            name='HistoricalCliente',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Modificado el')),
                ('codigo', models.CharField(max_length=50, verbose_name='Codigo')),
                ('cuit_cuil', models.CharField(blank=True, help_text='Solo se deben ingresar numeros', max_length=11, null=True, verbose_name='CUIT/CUIL')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre/ Razón Social')),
                ('contacto', models.CharField(blank=True, max_length=80, null=True, verbose_name='Nombre contacto')),
                ('direccion', models.CharField(max_length=80, null=True, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=80, null=True, verbose_name='Telefono')),
                ('email', models.EmailField(blank=True, max_length=264, null=True, verbose_name='Email')),
                ('web', models.URLField(blank=True, null=True, verbose_name='Web')),
                ('tipo', models.CharField(choices=[('p', 'Persona'), ('e', 'Empresa')], default='p', max_length=80, verbose_name='Tipo')),
                ('estado', models.CharField(choices=[('a', 'Activo'), ('i', 'Inactivo')], default='a', max_length=80, verbose_name='Estado')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='empresas.company', verbose_name='Compañía')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'historical cliente',
                'verbose_name_plural': 'historical clientes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
