# Generated by Django 5.2.17 on 2026-09-23 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0025_cliente_created_at_cliente_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Código postal'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='geo_provider',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Proveedor de geocodificación'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='geo_referencia_externa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Referencia externa de ubicación'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='geo_status',
            field=models.CharField(blank=True, choices=[('georreferenciado', 'Georreferenciado'), ('manual_legado', 'Manual (legado)'), ('manual_no_encontrado', 'Manual (no encontrado)')], max_length=25, null=True, verbose_name='Estado de georreferenciación'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='localidad',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Localidad'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='pais',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='provincia',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='historicalcliente',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Código postal'),
        ),
        migrations.AddField(
            model_name='historicalcliente',
            name='geo_provider',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Proveedor de geocodificación'),
        ),
        migrations.AddField(
            model_name='historicalcliente',
            name='geo_referencia_externa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Referencia externa de ubicación'),
        ),
        migrations.AddField(
            model_name='historicalcliente',
            name='geo_status',
            field=models.CharField(blank=True, choices=[('georreferenciado', 'Georreferenciado'), ('manual_legado', 'Manual (legado)'), ('manual_no_encontrado', 'Manual (no encontrado)')], max_length=25, null=True, verbose_name='Estado de georreferenciación'),
        ),
        migrations.AddField(
            model_name='historicalcliente',
            name='localidad',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Localidad'),
        ),
        migrations.AddField(
            model_name='historicalcliente',
            name='pais',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='historicalcliente',
            name='provincia',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(max_length=255, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='historicalcliente',
            name='direccion',
            field=models.CharField(max_length=255, null=True, verbose_name='Dirección'),
        ),
    ]
