# Generated by Django 4.0.4 on 2022-06-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matafuegos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipomatafuegos',
            name='vencimiento_carga',
            field=models.IntegerField(help_text='Cantidad de dias', verbose_name='Vencimiento de carga'),
        ),
        migrations.AlterField(
            model_name='tipomatafuegos',
            name='vencimiento_ph',
            field=models.IntegerField(help_text='Cantidad de dias', verbose_name='Vencimiento de PH'),
        ),
    ]
