# Generated by Django 4.0.4 on 2022-06-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matafuegos', '0002_alter_tipomatafuegos_vencimiento_carga_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matafuegos',
            name='direccion',
            field=models.CharField(max_length=20, null=True, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='matafuegos',
            name='localizacion',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Localizacion'),
        ),
        migrations.AlterField(
            model_name='matafuegos',
            name='patente',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Patente'),
        ),
    ]
