# Generated by Django 4.0.4 on 2022-06-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matafuegos', '0003_alter_matafuegos_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matafuegos',
            name='direccion',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Direccion'),
        ),
    ]
