# Generated by Django 4.0.4 on 2022-06-16 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matafuegos', '0005_matafuegos_numerointerno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipomatafuegos',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matafuegos.categoriamatafuegos'),
        ),
        migrations.AlterField(
            model_name='tipomatafuegos',
            name='peso',
            field=models.FloatField(blank=True, null=True, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='tipomatafuegos',
            name='vencimiento_carga',
            field=models.IntegerField(blank=True, help_text='Cantidad de dias', null=True, verbose_name='Vencimiento de carga'),
        ),
        migrations.AlterField(
            model_name='tipomatafuegos',
            name='vencimiento_ph',
            field=models.IntegerField(blank=True, help_text='Cantidad de dias', null=True, verbose_name='Vencimiento de PH'),
        ),
        migrations.AlterField(
            model_name='tipomatafuegos',
            name='volumen',
            field=models.FloatField(blank=True, null=True, verbose_name='Volumen'),
        ),
    ]
