# Generated by Django 4.0.4 on 2022-06-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matafuegos', '0006_alter_tipomatafuegos_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipomatafuegos',
            name='tipo',
            field=models.CharField(max_length=20, verbose_name='Tipo'),
        ),
    ]
