# Generated by Django 4.0.4 on 2022-06-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matafuegos', '0007_alter_tipomatafuegos_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matafuegos',
            name='direccion',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='matafuegos',
            name='localizacion',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Localizacion'),
        ),
    ]
