# Generated by Django 4.0.4 on 2022-06-21 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matafuegos', '0008_alter_matafuegos_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matafuegos',
            name='marca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='matafuegos.marcamatafuegos'),
        ),
    ]
