# Generated by Django 4.0.4 on 2022-06-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matafuegos', '0009_alter_matafuegos_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matafuegos',
            name='numero_dps',
            field=models.IntegerField(null=True, verbose_name='Numero de DPS'),
        ),
    ]
