# Generated by Django 4.0.4 on 2022-06-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matafuegos', '0010_alter_matafuegos_numero_dps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matafuegos',
            name='fecha_fabricacion',
            field=models.DateField(null=True, verbose_name='Fecha de fabricacion'),
        ),
    ]
