# Generated by Django 4.0.4 on 2022-06-21 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matafuegos', '0011_alter_matafuegos_fecha_fabricacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matafuegos',
            name='fecha_carga',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='Fecha de carga'),
        ),
        migrations.AlterField(
            model_name='matafuegos',
            name='fecha_ph',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='Fecha de PH'),
        ),
    ]
