# Generated by Django 4.0.4 on 2022-07-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matafuegos', '0012_alter_matafuegos_fecha_carga_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matafuegos',
            name='fecha_fabricacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de fabricacion'),
        ),
    ]
