# Generated by Django 4.0.4 on 2022-07-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matafuegos', '0013_alter_matafuegos_fecha_fabricacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matafuegos',
            name='categoria',
            field=models.CharField(choices=[('v', 'Vehicular'), ('d', 'Domiciliario'), ('ma', 'Maquinaria Agricola')], max_length=12, verbose_name='Categoria'),
        ),
    ]
