# Generated by Django 4.0.4 on 2022-07-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matafuegos', '0014_alter_matafuegos_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matafuegos',
            name='numero_dps',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numero de DPS'),
        ),
    ]
