# Generated by Django 4.0.4 on 2022-07-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matafuegos', '0016_alter_matafuegos_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matafuegos',
            name='patente',
            field=models.CharField(blank=True, max_length=19, null=True, verbose_name='Patente'),
        ),
    ]
