# Generated by Django 4.0.4 on 2022-07-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matafuegos', '0017_alter_matafuegos_patente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matafuegos',
            name='fecha_fabricacion',
            field=models.DateField(null=True, verbose_name='Fecha de fabricacion'),
        ),
    ]
