# Generated by Django 4.0.4 on 2022-07-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matafuegos', '0019_matafuegos_vencido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matafuegos',
            name='numero',
            field=models.IntegerField(blank=True, verbose_name='Numero'),
        ),
    ]
