# Generated by Django 4.0.4 on 2022-08-30 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0011_alter_cliente_web'),
        ('matafuegos', '0021_alter_matafuegos_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matafuegos',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cliente.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='matafuegos',
            name='marca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='matafuegos.marcamatafuegos', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='matafuegos',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matafuegos.tipomatafuegos', verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='tipomatafuegos',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matafuegos.categoriamatafuegos', verbose_name='Categoria'),
        ),
    ]
