# Generated by Django 4.0.4 on 2022-09-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matafuegos', '0022_alter_matafuegos_cliente_alter_matafuegos_marca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matafuegos',
            name='numero_dps',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numero de DPS'),
        ),
    ]
