# Generated by Django 4.0.4 on 2022-10-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matafuegos', '0023_alter_matafuegos_numero_dps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matafuegos',
            name='localizacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Localizacion'),
        ),
    ]
