# Generated by Django 4.2.5 on 2026-08-31 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('matafuegos', '0024_alter_matafuegos_localizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='matafuegos',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matafuegos', to='empresas.company', verbose_name='Compañía'),
        ),
    ]
