# Generated by Django 5.2.17 on 2026-09-02 19:27

import datetime
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0025_cliente_created_at_cliente_created_by_and_more'),
        ('empresas', '0003_remove_company_fecha_creacion_company_created_at_and_more'),
        ('matafuegos', '0032_alter_matafuegos_cliente_final'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='matafuegos',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 9, 2, 19, 27, 26, 389342, tzinfo=datetime.timezone.utc), verbose_name='Creado el'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matafuegos',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='matafuegos',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado el'),
        ),
        migrations.AddField(
            model_name='matafuegos',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.CreateModel(
            name='HistoricalMatafuegos',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Modificado el')),
                ('numero', models.IntegerField(verbose_name='Numero')),
                ('numeroInterno', models.IntegerField(blank=True, null=True, verbose_name='Numero interno')),
                ('patente', models.CharField(blank=True, max_length=19, null=True, verbose_name='Patente')),
                ('direccion', models.CharField(blank=True, max_length=30, null=True, verbose_name='Direccion')),
                ('localizacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Localizacion')),
                ('numero_localizacion', models.IntegerField(blank=True, null=True, verbose_name='Numero de localizacion')),
                ('categoria', models.CharField(choices=[('v', 'Vehicular'), ('d', 'Domiciliario'), ('ma', 'Maquinaria Agricola')], max_length=20, verbose_name='Categoria')),
                ('fecha_fabricacion', models.DateField(null=True, verbose_name='Fecha de fabricacion')),
                ('fecha_carga', models.DateField(default=datetime.date.today, null=True, verbose_name='Fecha de carga')),
                ('fecha_ph', models.DateField(default=datetime.date.today, null=True, verbose_name='Fecha de PH')),
                ('numero_dps', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numero de DPS')),
                ('fecha_proxima_carga', models.DateField(blank=True, null=True, verbose_name='Fecha de proxima carga')),
                ('fecha_proxima_ph', models.DateField(blank=True, null=True, verbose_name='Fecha de proxima PH')),
                ('vencido', models.BooleanField(default=False, verbose_name='Vencido')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cliente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cliente.cliente', verbose_name='Cliente')),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='empresas.company', verbose_name='Compañía')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('marca', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='matafuegos.marcamatafuegos', verbose_name='Marca')),
                ('tipo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='matafuegos.tipomatafuegos', verbose_name='Tipo')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'historical matafuegos',
                'verbose_name_plural': 'historical Matafuegos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
