# Generated by Django 5.2.17 on 2026-09-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matafuegos', '0033_matafuegos_created_at_matafuegos_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmatafuegos',
            name='estado',
            field=models.CharField(choices=[('a', 'Activo'), ('i', 'Inactivo')], default='a', max_length=80, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='matafuegos',
            name='estado',
            field=models.CharField(choices=[('a', 'Activo'), ('i', 'Inactivo')], default='a', max_length=80, verbose_name='Estado'),
        ),
    ]
