# Generated by Django 5.2.17 on 2026-09-23 13:56

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matafuegos', '0034_historicalmatafuegos_estado_matafuegos_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalNotificacionVencimiento',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Modificado el')),
                ('tipo_vencimiento', models.CharField(choices=[('carga', 'Próxima carga'), ('ph', 'Próxima PH')], max_length=20, verbose_name='Tipo de vencimiento')),
                ('fecha_vencimiento', models.DateField(verbose_name='Vencimiento informado')),
                ('medio', models.CharField(choices=[('whatsapp', 'WhatsApp')], default='whatsapp', max_length=20, verbose_name='Medio')),
                ('numero_destino', models.CharField(max_length=30, verbose_name='Número de destino')),
                ('mensaje', models.TextField(blank=True, verbose_name='Mensaje')),
                ('estado_envio', models.CharField(choices=[('pendiente', 'Pendiente de confirmación'), ('notificada', 'Notificada'), ('error', 'Error')], default='pendiente', max_length=20, verbose_name='Estado del envío')),
                ('external_message_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID externo del mensaje')),
                ('observacion', models.TextField(blank=True, verbose_name='Observación')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('matafuego', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='matafuegos.matafuegos', verbose_name='Matafuego')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'historical Notificación de vencimiento',
                'verbose_name_plural': 'historical Notificaciones de vencimiento',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='NotificacionVencimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado el')),
                ('tipo_vencimiento', models.CharField(choices=[('carga', 'Próxima carga'), ('ph', 'Próxima PH')], max_length=20, verbose_name='Tipo de vencimiento')),
                ('fecha_vencimiento', models.DateField(verbose_name='Vencimiento informado')),
                ('medio', models.CharField(choices=[('whatsapp', 'WhatsApp')], default='whatsapp', max_length=20, verbose_name='Medio')),
                ('numero_destino', models.CharField(max_length=30, verbose_name='Número de destino')),
                ('mensaje', models.TextField(blank=True, verbose_name='Mensaje')),
                ('estado_envio', models.CharField(choices=[('pendiente', 'Pendiente de confirmación'), ('notificada', 'Notificada'), ('error', 'Error')], default='pendiente', max_length=20, verbose_name='Estado del envío')),
                ('external_message_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID externo del mensaje')),
                ('observacion', models.TextField(blank=True, verbose_name='Observación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('matafuego', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notificaciones', to='matafuegos.matafuegos', verbose_name='Matafuego')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Notificación de vencimiento',
                'verbose_name_plural': 'Notificaciones de vencimiento',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['matafuego', 'tipo_vencimiento', 'fecha_vencimiento', 'estado_envio'], name='matafuegos_notif_ciclo_idx')],
            },
        ),
    ]
