# Generated by Django 4.0.4 on 2022-05-31 13:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('matafuegos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordenes_de_trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(default=datetime.date.today, verbose_name='Fecha de creacioin de orden')),
                ('fecha_inicio', models.DateField(default=datetime.date.today, verbose_name='Fecha de inicio')),
                ('fecha_entrega', models.DateField(default=datetime.date.today, verbose_name='Entrega estimada')),
                ('fecha_cierre', models.DateField(blank=True, null=True, verbose_name='Fecha de cierre')),
                ('estado', models.CharField(choices=[('p', 'Pendiente'), ('ep', 'En proceso'), ('f', 'Finalizada'), ('c', 'cancelada')], default='p', max_length=80, verbose_name='Estado')),
                ('monto_total', models.FloatField(default=0, verbose_name='Monto')),
                ('notas', models.CharField(blank=True, max_length=80, verbose_name='notas')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
                ('matafuegos', models.ForeignKey(help_text='Se puede buscar por numero de cliente, de matafuegos y numero de DPS', on_delete=django.db.models.deletion.CASCADE, to='matafuegos.matafuegos')),
            ],
            options={
                'verbose_name_plural': 'Ordenes de trabajo',
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('precio', models.FloatField(default=0, verbose_name='Precio')),
            ],
        ),
        migrations.CreateModel(
            name='TareaOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precioAj', models.FloatField(default=0, verbose_name='precio ajustable')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orden_trabajo.ordenes_de_trabajo')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orden_trabajo.tarea')),
            ],
            options={
                'verbose_name_plural': 'Tarea - Orden de trabajo',
            },
        ),
    ]
