# Generated by Django 4.0.4 on 2022-06-14 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matafuegos', '0002_alter_tipomatafuegos_vencimiento_carga_and_more'),
        ('orden_trabajo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenes_de_trabajo',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='ordenes_de_trabajo',
            name='matafuegos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matafuegos.matafuegos'),
        ),
    ]
