# Generated by Django 4.0.4 on 2022-07-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_trabajo', '0002_alter_ordenes_de_trabajo_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenes_de_trabajo',
            name='impresa',
            field=models.BooleanField(default=0, verbose_name='Impresa'),
        ),
        migrations.AlterField(
            model_name='ordenes_de_trabajo',
            name='notas',
            field=models.CharField(blank=True, max_length=80, verbose_name='Notas'),
        ),
    ]
