# Generated by Django 4.0.4 on 2022-07-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_trabajo', '0003_ordenes_de_trabajo_impresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareaorden',
            name='cant_cargada',
            field=models.FloatField(default=0, verbose_name='Cantidad Cargada'),
        ),
    ]
