# Generated by Django 4.0.4 on 2022-07-11 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_trabajo', '0004_tareaorden_cant_cargada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenes_de_trabajo',
            name='estado',
            field=models.CharField(choices=[('p', 'Pendiente'), ('ep', 'En proceso'), ('f', 'Finalizada'), ('c', 'cancelada')], default='ep', max_length=80, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='ordenes_de_trabajo',
            name='fecha_inicio',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Fecha de inicio'),
        ),
    ]
