# Generated by Django 4.0.4 on 2022-07-14 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orden_trabajo', '0007_alter_ordenes_de_trabajo_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenes_de_trabajo',
            name='impresa',
        ),
    ]
