# Generated by Django 4.0.4 on 2022-08-30 15:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0011_alter_cliente_web'),
        ('matafuegos', '0022_alter_matafuegos_cliente_alter_matafuegos_marca_and_more'),
        ('orden_trabajo', '0009_ordenes_de_trabajo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenes_de_trabajo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='ordenes_de_trabajo',
            name='fecha_creacion',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de creacion de orden'),
        ),
        migrations.AlterField(
            model_name='ordenes_de_trabajo',
            name='matafuegos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matafuegos.matafuegos', verbose_name='Matafuegos'),
        ),
        migrations.AlterField(
            model_name='ordenes_de_trabajo',
            name='usuario',
            field=models.CharField(default='', max_length=30, verbose_name='Usuario responsable'),
        ),
        migrations.AlterField(
            model_name='tareaorden',
            name='cant_cargada',
            field=models.FloatField(default=0, verbose_name='Cantidad cargada'),
        ),
        migrations.AlterField(
            model_name='tareaorden',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orden_trabajo.ordenes_de_trabajo', verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='tareaorden',
            name='precioAj',
            field=models.FloatField(default=0, verbose_name='Precio ajustable'),
        ),
        migrations.AlterField(
            model_name='tareaorden',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orden_trabajo.tarea', verbose_name='Tarea'),
        ),
    ]
