# Generated by Django 4.2.5 on 2026-08-31 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('orden_trabajo', '0010_alter_ordenes_de_trabajo_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenes_de_trabajo',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_de_trabajo', to='empresas.company', verbose_name='Compañía'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tareas', to='empresas.company', verbose_name='Compañía'),
        ),
    ]
