# Generated by Django 4.2.5 on 2026-09-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_trabajo', '0019_alter_ordenes_de_trabajo_matafuegos'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='es_recarga',
            field=models.BooleanField(default=False, help_text='Marca esta tarea como recarga: una orden solo puede emitir su oblea DPS al finalizarse si incluye alguna tarea marcada así.', verbose_name='Es tarea de recarga'),
        ),
    ]
