# Generated by Django 5.2.17 on 2026-09-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_trabajo', '0022_ordenes_de_trabajo_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalordenes_de_trabajo',
            name='numero_dps',
            field=models.CharField(blank=True, help_text='Numero de DPS asignado al emitir la oblea, si la orden incluyo una tarea de recarga.', max_length=50, null=True, verbose_name='Numero de DPS'),
        ),
        migrations.AddField(
            model_name='ordenes_de_trabajo',
            name='numero_dps',
            field=models.CharField(blank=True, help_text='Numero de DPS asignado al emitir la oblea, si la orden incluyo una tarea de recarga.', max_length=50, null=True, verbose_name='Numero de DPS'),
        ),
    ]
