# Generated by Django 4.2.5 on 2026-08-31 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Logo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('veh_inicio', models.IntegerField(default=0, verbose_name='VEH inicio')),
                ('veh_fin', models.IntegerField(default=0, verbose_name='VEH fin')),
                ('veh_prefijo', models.CharField(default='', max_length=5, verbose_name='VEH prefijo')),
                ('veh_actual', models.IntegerField(default=0, verbose_name='VEH actual')),
                ('dom_inicio', models.IntegerField(default=0, verbose_name='DOM inicio')),
                ('dom_fin', models.IntegerField(default=0, verbose_name='DOM fin')),
                ('dom_prefijo', models.CharField(default='', max_length=5, verbose_name='DOM prefijo')),
                ('dom_actual', models.IntegerField(default=0, verbose_name='DOM actual')),
                ('smtp_email', models.EmailField(blank=True, max_length=264, null=True, verbose_name='Email')),
                ('smtp_password', models.CharField(blank=True, max_length=20, null=True, verbose_name='Contraseña')),
            ],
            options={
                'verbose_name': 'Compañía',
                'verbose_name_plural': 'Compañías',
            },
        ),
    ]
