# Generated by Django 5.2.17 on 2026-09-02 19:01

import datetime
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_create_initial_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 9, 2, 19, 1, 15, 198393, tzinfo=datetime.timezone.utc), verbose_name='Creado el'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado el'),
        ),
        migrations.AddField(
            model_name='company',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.CreateModel(
            name='HistoricalCompany',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Modificado el')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('logo', models.TextField(blank=True, max_length=100, null=True, verbose_name='Logo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('veh_inicio', models.IntegerField(default=0, verbose_name='VEH inicio')),
                ('veh_fin', models.IntegerField(default=0, verbose_name='VEH fin')),
                ('veh_prefijo', models.CharField(default='', max_length=5, verbose_name='VEH prefijo')),
                ('veh_actual', models.IntegerField(default=0, verbose_name='VEH actual')),
                ('dom_inicio', models.IntegerField(default=0, verbose_name='DOM inicio')),
                ('dom_fin', models.IntegerField(default=0, verbose_name='DOM fin')),
                ('dom_prefijo', models.CharField(default='', max_length=5, verbose_name='DOM prefijo')),
                ('dom_actual', models.IntegerField(default=0, verbose_name='DOM actual')),
                ('smtp_email', models.EmailField(blank=True, max_length=264, null=True, verbose_name='Email')),
                ('smtp_password', models.CharField(blank=True, max_length=20, null=True, verbose_name='Contraseña')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'historical Compañía',
                'verbose_name_plural': 'historical Compañías',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
