# Generated by Django 5.2.17 on 2026-09-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_remove_company_fecha_creacion_company_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='numero_recargador',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Número de recargador'),
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='numero_recargador',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Número de recargador'),
        ),
    ]
